services:
  - type: web
    name: spring-boot-app
    env: java
    plan: free
    branch: main
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    autoDeploy: true
